name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _python_abi3_support
  - alsa-lib
  - anndata
  - anyio
  - aom
  - argon2-cffi
  - argon2-cffi-bindings
  - arpack
  - array-api-compat
  - arrow
  - asttokens
  - async-lru
  - attr
  - attrs
  - babel
  - backports.zstd
  - beautifulsoup4
  - bleach
  - bleach-with-css
  - blosc
  - bqplot
  - brotli
  - brotli-bin
  - brotli-python
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - certifi
  - cffi
  - cftime
  - charls
  - charset-normalizer
  - colorama
  - comm
  - contourpy
  - cpython
  - cycler
  - cyrus-sasl
  - dav1d
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - deprecated
  - donfig
  - double-conversion
  - exceptiongroup
  - executing
  - ffmpeg
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freeglut
  - freetype
  - fribidi
  - gdk-pixbuf
  - giflib
  - glpk
  - glslang
  - gmp
  - google-crc32c
  - graphite2
  - h11
  - h2
  - h5py
  - harfbuzz
  - hdf4
  - hdf5
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - igraph
  - imagecodecs
  - imageio
  - imath
  - importlib-metadata
  - importlib_resources
  - intel-gmmlib
  - intel-media-driver
  - ipydatawidgets
  - ipykernel
  - ipython
  - ipython_genutils
  - ipython_pygments_lexers
  - ipyvolume
  - ipyvue
  - ipyvuetify
  - ipywebrtc
  - ipywidgets
  - isoduration
  - jasper
  - jedi
  - jinja2
  - joblib
  - json5
  - jsonpickle
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - jxrlib
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lark
  - lazy-loader
  - lcms2
  - ld_impl_linux-64
  - legacy-api-wrap
  - lerc
  - level-zero
  - libabseil
  - libaec
  - libass
  - libavif16
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang-cpp21.1
  - libclang13
  - libcrc32c
  - libcups
  - libcurl
  - libdeflate
  - libdrm
  - libedit
  - libegl
  - libev
  - libexpat
  - libffi
  - libflac
  - libfreetype
  - libfreetype6
  - libgcc
  - libgcc-ng
  - libgfortran
  - libgfortran5
  - libgl
  - libglib
  - libglu
  - libglvnd
  - libglx
  - libgomp
  - libhwloc
  - libhwy
  - libiconv
  - libjpeg-turbo
  - libjxl
  - liblapack
  - liblapacke
  - libllvm21
  - liblzma
  - libmpdec
  - libnetcdf
  - libnghttp2
  - libntlm
  - libogg
  - libopenblas
  - libopencv
  - libopengl
  - libopenvino
  - libopenvino-auto-batch-plugin
  - libopenvino-auto-plugin
  - libopenvino-hetero-plugin
  - libopenvino-intel-cpu-plugin
  - libopenvino-intel-gpu-plugin
  - libopenvino-intel-npu-plugin
  - libopenvino-ir-frontend
  - libopenvino-onnx-frontend
  - libopenvino-paddle-frontend
  - libopenvino-pytorch-frontend
  - libopenvino-tensorflow-frontend
  - libopenvino-tensorflow-lite-frontend
  - libopus
  - libpciaccess
  - libpng
  - libpq
  - libprotobuf
  - librsvg
  - libsndfile
  - libsodium
  - libsqlite
  - libssh2
  - libstdcxx
  - libstdcxx-ng
  - libsystemd0
  - libtiff
  - libudev1
  - libunwind
  - liburing
  - libusb
  - libuuid
  - libva
  - libvorbis
  - libvpl
  - libvpx
  - libvulkan-loader
  - libwebp-base
  - libxcb
  - libxcrypt
  - libxkbcommon
  - libxml2
  - libxml2-16
  - libxml2-devel
  - libxslt
  - libzip
  - libzlib
  - libzopfli
  - llvmlite
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mpg123
  - msgpack-python
  - munkres
  - natsort
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - netcdf4
  - networkx
  - nomkl
  - notebook
  - notebook-shim
  - numba
  - numcodecs
  - numexpr
  - numpy
  - ocl-icd
  - opencl-headers
  - opencv
  - openexr
  - openh264
  - openjpeg
  - openjph
  - openldap
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - pango
  - parso
  - patsy
  - pcre2
  - pexpect
  - pillow
  - pip
  - pixman
  - platformdirs
  - pooch
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pugixml
  - pulseaudio-client
  - pure_eval
  - py-cpuinfo
  - py-opencv
  - pycparser
  - pygments
  - pynndescent
  - pyparsing
  - pyreadr
  - pyside6
  - pysocks
  - pytables
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-gil
  - python-igraph
  - python-json-logger
  - python-tzdata
  - python_abi
  - pythreejs
  - pytz
  - pyvis
  - pywavelets
  - pyyaml
  - pyzmq
  - qhull
  - qt6-main
  - rav1e
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rfc3987-syntax
  - rpds-py
  - scanpy
  - scikit-image
  - scikit-learn
  - scipy
  - sdl2
  - sdl3
  - seaborn
  - seaborn-base
  - send2trash
  - session-info2
  - setuptools
  - shaderc
  - six
  - snappy
  - sniffio
  - soupsieve
  - spirv-tools
  - stack_data
  - statsmodels
  - svt-av1
  - tbb
  - terminado
  - texttable
  - threadpoolctl
  - tifffile
  - tinycss2
  - tk
  - tomli
  - tornado
  - tqdm
  - traitlets
  - traittypes
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - umap-learn
  - uri-template
  - urllib3
  - wayland
  - wayland-protocols
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - widgetsnbextension
  - wrapt
  - x264
  - x265
  - xcb-util
  - xcb-util-cursor
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xkeyboard-config
  - xmltodict
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxcomposite
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrandr
  - xorg-libxrender
  - xorg-libxscrnsaver
  - xorg-libxtst
  - xorg-libxxf86vm
  - yaml
  - zarr
  - zeromq
  - zfp
  - zipp
  - zlib
  - zlib-ng
  - zstd
  - pip:
      - leidenalg
      - python-mnist
      - zss