"""
phase2_hyperparameter_study.ipynb content generator
This creates a structured experimentation notebook for Phase 2 improvements.
"""

# This is a template - will be used to generate the notebook cells

import json

notebook_cells = [
    {
        "cell_type": "markdown",
        "source": [
            "# Phase 2 Hyperparameter Optimization Study\n",
            "\n",
            "Goal: Improve Phase 2 hard-label validation accuracy from 75.74% to 80%+\n",
            "\n",
            "Strategy:\n",
            "1. **Stage 1**: Architecture comparison (ResNet, Wide, Attention vs baseline)\n",
            "2. **Stage 2**: Expanded CV hyperparameter search with all combinations\n",
            "3. **Stage 3**: Ensemble methods on best configurations\n",
            "4. **Stage 4**: Ablation studies to validate improvements\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "import numpy as np\n",
            "import pandas as pd\n",
            "import torch\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "from tqdm import tqdm\n",
            "from collections import defaultdict\n",
            "import pickle\n",
            "import os\n",
            "from bundle_paths import (\n",
            "    CELL_LINEAGE_PATH,\n",
            "    CELL_TYPE_CSV,\n",
            "    PHASE2_OPTIMIZATION_SUMMARY_CSV,\n",
            "    PHASE2_STAGE2_PLOT,\n",
            "    S3_CSV,\n",
            "    ensure_repo_on_path,\n",
            "    ensure_results_dir,\n",
            ")\n",
            "\n",
            "sns.set_style('whitegrid')\n",
            "plt.rcParams['figure.dpi'] = 150\n",
            "\n",
            "ensure_repo_on_path()\n",
            "ensure_results_dir()\n",
            "\n",
            "from feature_selection import (\n",
            "    cross_validate_features,\n",
            "    eval_prediction_metrics,\n",
            "    build_focused_classifier,\n",
            "    train_focused,\n",
            "    entropy_based_weights,\n",
            ")\n",
            "from phase2_improved_cv import cross_validate_focused_improved\n",
            "\n",
            "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "print(f'Device: {device}')\n"
        ]
    },
    {
        "cell_type": "markdown",
        "source": [
            "## Load Data and Phase 1 Results\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "# Load the data (from protein_feature_select.ipynb)\n",
            "import json\n",
            "from collections import defaultdict\n",
            "from pyreadr import read_r\n",
            "import pandas as pd\n",
            "\n",
            "with CELL_LINEAGE_PATH.open('r', encoding='utf-8') as f:\n",
            "    lineage_data = json.load(f)\n",
            "\n",
            "def map_names(did):\n",
            "    if   did == \"P4a\": return \"Z3\"\n",
            "    elif did == \"P4p\": return \"Z2\"\n",
            "    elif did == \"P0a\": return \"AB\"\n",
            "    else: return did\n",
            "\n",
            "terminal_nodes = []\n",
            "intermediate_nodes = []\n",
            "descendant_list_dict = defaultdict(list)\n",
            "\n",
            "def dfs(node, parent, ancestors=[]):\n",
            "    children = node.get(\"children\", [])\n",
            "    lookup_name = map_names(node[\"did\"])\n",
            "    if len(children) == 0 :\n",
            "        terminal_nodes.append(lookup_name)\n",
            "        for ancestor in ancestors:\n",
            "            descendant_list_dict[ancestor].append(lookup_name)\n",
            "    else:\n",
            "        intermediate_nodes.append(lookup_name)\n",
            "        for child in children:\n",
            "            dfs(child, node, ancestors + [lookup_name])\n",
            "\n",
            "dfs(lineage_data, None)\n",
            "\n",
            "# Load protein expression and cell types\n",
            "cell_type_df = pd.read_csv(CELL_TYPE_CSV)\n",
            "protein_exp = pd.read_csv(S3_CSV, index_col=0).T\n",
            "protein_exp = protein_exp.fillna(0)\n",
            "protein_exp = protein_exp[(protein_exp != 0).any(axis=1)]\n",
            "protein_exp_zscore = protein_exp.apply(lambda x: (x - x.mean()) / x.std(), axis=1)\n",
            "\n",
            "print(f'Protein expression shape: {protein_exp_zscore.shape}')\n",
            "print(f'Terminal nodes: {len(terminal_nodes)}, Intermediate: {len(intermediate_nodes)}')\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "# Build cell type mappings (from notebook)\n",
            "cell_type_dict = {}\n",
            "for node in terminal_nodes:\n",
            "    cur_cell_type_df = cell_type_df[cell_type_df['wormweb.lineage'] == node]\n",
            "    if len(cur_cell_type_df) == 0:\n",
            "        continue\n",
            "    cur_lineage_types = cur_cell_type_df[\"wormweb.type\"]\n",
            "    cur_lineage_types = cur_lineage_types[~cur_lineage_types.isna()].unique()\n",
            "    if len(cur_lineage_types) == 0:\n",
            "        cell_type_dict[node] = \"programmed_death\"\n",
            "        continue\n",
            "    cur_type = cur_lineage_types[0]\n",
            "    cell_type_dict[node] = cur_type\n",
            "\n",
            "cell_types = list(set(cell_type_dict.values()))\n",
            "cell_types = [ct for ct in cell_types if ct != \"programmed_death\"]\n",
            "cell_types = sorted(cell_types, key=lambda x: sum([1 for v in cell_type_dict.values() if v == x]), reverse=True)\n",
            "cell_types.append(\"programmed_death\")\n",
            "cell_type_to_int = {ct: i for i, ct in enumerate(cell_types)}\n",
            "\n",
            "# Build soft labels\n",
            "cell_type_one_hot = {}\n",
            "for node, ct in cell_type_dict.items():\n",
            "    one_hot = np.zeros(len(cell_types))\n",
            "    one_hot[cell_type_to_int[ct]] = 1\n",
            "    cell_type_one_hot[node] = one_hot\n",
            "\n",
            "for node in intermediate_nodes:\n",
            "    descendant_types = [cell_type_one_hot[desc] for desc in descendant_list_dict[node]]\n",
            "    if len(descendant_types) == 0:\n",
            "        cell_type_one_hot[node] = np.zeros(len(cell_types))\n",
            "        continue\n",
            "    summed_types = np.sum(descendant_types, axis=0)\n",
            "    normalized_types = summed_types / np.sum(summed_types)\n",
            "    cell_type_one_hot[node] = normalized_types\n",
            "\n",
            "X = protein_exp_zscore.values.T\n",
            "y = np.array([cell_type_one_hot[map_names(node)] for node in protein_exp_zscore.columns])\n",
            "n_descendants = np.array([len(descendant_list_dict[map_names(node)]) for node in protein_exp_zscore.columns])\n",
            "\n",
            "sample_weights_v2 = entropy_based_weights(y, alpha=3.0)\n",
            "terminal_mask = np.array([len(descendant_list_dict[map_names(node)]) == 0 for node in protein_exp_zscore.columns])\n",
            "\n",
            "print(f'Data shape: X={X.shape}, y={y.shape}')\n",
            "print(f'Terminal (hard): {terminal_mask.sum()}, Intermediate (soft): {(~terminal_mask).sum()}')\n",
            "print(f'Number of classes: {len(cell_types)}')\n"
        ]
    },
    {
        "cell_type": "markdown",
        "source": [
            "## Stage 1: Architecture Comparison\n",
            "\n",
            "Test ResNet, Wide, and Attention architectures on current-best Phase 2 hyperparameters.\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "# Use best Phase 1 and Phase 2 configuration from protein_feature_select.ipynb\n",
            "best_selector_config = {\n",
            "    'l1_lambda': 0.004,\n",
            "    'hidden_dims': (128, 64),\n",
            "    'dropout': 0.2,\n",
            "}\n",
            "\n",
            "# Current best Phase 2 config (baseline)\n",
            "baseline_config = {\n",
            "    'n_select': 25,\n",
            "    'hidden_dims': (32,),\n",
            "    'dropout': 0.2,\n",
            "    'dist_lambda': 0.1,\n",
            "    'model_type': 'focused',\n",
            "    'optimizer_type': 'adam',\n",
            "    'lr': 1e-3,\n",
            "}\n",
            "\n",
            "print(f'Baseline Phase 2 config:')\n",
            "for k, v in baseline_config.items():\n",
            "    print(f'  {k}: {v}')\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "# Stage 1: Test each architecture type with baseline hyperparams\n",
            "print('\\n=== STAGE 1: Architecture Comparison ===')\n",
            "\n",
            "STAGE1_PARAM_GRID = {\n",
            "    'n_select': [25],\n",
            "    'hidden_dims': [(128, 64)],  # Wider/deeper than baseline (32,)\n",
            "    'dropout': [0.2],\n",
            "    'dist_lambda': [0.0],  # Test without dist_lambda constraint first\n",
            "    'model_type': ['focused', 'resnet', 'wide', 'attention'],\n",
            "    'optimizer_type': ['adam'],\n",
            "    'lr': [1e-3],\n",
            "}\n",
            "\n",
            "print(f'Testing {len(STAGE1_PARAM_GRID[\"model_type\"])} architectures with 5-fold CV...')\n",
            "\n",
            "stage1_results, stage1_best = cross_validate_focused_improved(\n",
            "    X, y, sample_weights_v2, terminal_mask,\n",
            "    selector_config=best_selector_config,\n",
            "    param_grid=STAGE1_PARAM_GRID,\n",
            "    n_splits=5,\n",
            "    selector_epochs=250,\n",
            "    focused_epochs=400,\n",
            "    seed=42,\n",
            "    device=str(device),\n",
            ")\n",
            "\n",
            "# Summarize results\n",
            "stage1_df = pd.DataFrame([\n",
            "    {\n",
            "        'model_type': r['config'].get('model_type', 'focused'),\n",
            "        'mean_val_acc': r['summary']['mean_val_acc'],\n",
            "        'mean_overfit_gap': r['summary']['mean_overfit_gap'],\n",
            "        'soft_target_prob': r['summary']['mean_expected_target_probability'],\n",
            "        'score': r['score'],\n",
            "    }\n",
            "    for r in stage1_results\n",
            "])\n",
            "\n",
            "print('\\nStage 1 Results:') \n",
            "print(stage1_df.to_string(index=False))\n",
            "print(f'\\nBest architecture: {stage1_best[\"model_type\"]}')\n",
            "print(f'  Validation accuracy: {stage1_results[0][\"summary\"][\"mean_val_acc\"]:.4f}')\n"
        ]
    },
    {
        "cell_type": "markdown",
        "source": [
            "## Stage 2: Expanded Hyperparameter Grid Search\n",
            "\n",
            "Now test combinations of improved architectures with wider hyperparameter ranges.\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "print('\\n=== STAGE 2: Expanded Hyperparameter Grid ===')\n",
            "\n",
            "# Get best model type from Stage 1\n",
            "best_model_type = stage1_results[0]['config']['model_type']\n",
            "improvement_from_stage1 = stage1_results[0]['summary']['mean_val_acc'] - 0.7574\n",
            "\n",
            "print(f'Stage 1 winner: {best_model_type} (+{improvement_from_stage1*100:.2f}% vs baseline)')\n",
            "print(f'Now expanding grid with promising hyperparameters...')\n",
            "\n",
            "STAGE2_PARAM_GRID = {\n",
            "    'n_select': [20, 25, 30],                                    # Vary K\n",
            "    'hidden_dims': [(64, 64), (128, 64), (128, 128, 64), (256, 128, 64)],  # Wider/deeper\n",
            "    'dropout': [0.0, 0.1, 0.2, 0.3],                            # Wider dropout range\n",
            "    'dist_lambda': [0.0, 0.05, 0.1],                           # Try removing/reducing constraint\n",
            "    'model_type': [best_model_type],                            # Use Stage 1 winner\n",
            "    'optimizer_type': ['adam', 'adamw'],                        # Test AdamW\n",
            "    'lr': [5e-4, 1e-3, 2e-3],                                   # Wider LR range\n",
            "    'label_smoothing': [0.0, 0.1],                              # Test label smoothing\n",
            "}\n",
            "\n",
            "n_configs_stage2 = np.prod([len(v) for v in STAGE2_PARAM_GRID.values()])\n",
            "print(f'Grid size: {n_configs_stage2} configurations')\n",
            "print(f'\\nStage 2 CV (patience: ~30 min for {n_configs_stage2} configs with 5 folds)...')\n",
            "\n",
            "stage2_results, stage2_best = cross_validate_focused_improved(\n",
            "    X, y, sample_weights_v2, terminal_mask,\n",
            "    selector_config=best_selector_config,\n",
            "    param_grid=STAGE2_PARAM_GRID,\n",
            "    n_splits=5,\n",
            "    selector_epochs=250,\n",
            "    focused_epochs=400,\n",
            "    seed=42,\n",
            "    device=str(device),\n",
            ")\n",
            "\n",
            "print(f'\\n=== Stage 2 Complete ===')\n",
            "best_stage2_acc = stage2_results[0]['summary']['mean_val_acc']\n",
            "print(f'Best accuracy: {best_stage2_acc:.4f}')\n",
            "print(f'Improvement from baseline (0.7574): +{(best_stage2_acc - 0.7574)*100:.2f}%')\n",
            "print(f'\\nBest config:')\n",
            "for k, v in stage2_best.items():\n",
            "    print(f'  {k}: {v}')\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "# Show top configurations from Stage 2\n",
            "stage2_df = pd.DataFrame([\n",
            "    {\n",
            "        'n_select': r['config']['n_select'],\n",
            "        'hidden_dims': str(r['config']['hidden_dims']),\n",
            "        'dropout': r['config']['dropout'],\n",
            "        'lr': r['config']['lr'],\n",
            "        'dist_lambda': r['config']['dist_lambda'],\n",
            "        'label_smoothing': r['config'].get('label_smoothing', 0.0),\n",
            "        'optimizer': r['config'].get('optimizer_type', 'adam'),\n",
            "        'val_acc': r['summary']['mean_val_acc'],\n",
            "        'overfit_gap': r['summary']['mean_overfit_gap'],\n",
            "        'soft_target': r['summary']['mean_expected_target_probability'],\n",
            "        'score': r['score'],\n",
            "    }\n",
            "    for r in stage2_results[:10]  # Top 10\n",
            "])\n",
            "\n",
            "print('\\nTop 10 Stage 2 Configurations:')\n",
            "print(stage2_df.to_string(index=False))\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "# Visualization: Distribution of validation accuracies\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "all_accs_stage2 = [r['summary']['mean_val_acc'] for r in stage2_results]\n",
            "\n",
            "axes[0].hist(all_accs_stage2, bins=30, color='steelblue', edgecolor='white', alpha=0.7)\n",
            "axes[0].axvline(best_stage2_acc, color='red', linestyle='--', linewidth=2, label=f'Best: {best_stage2_acc:.4f}')\n",
            "axes[0].axvline(0.7574, color='orange', linestyle='--', linewidth=2, label='Baseline: 0.7574')\n",
            "axes[0].set_xlabel('Validation Accuracy')\n",
            "axes[0].set_ylabel('Count')\n",
            "axes[0].set_title('Stage 2: Distribution of CV accuracies')\n",
            "axes[0].legend()\n",
            "\n",
            "# Scatter: accuracy vs overfit gap\n",
            "scatter_data = [(r['summary']['mean_val_acc'], r['summary']['mean_overfit_gap'], r['score']) for r in stage2_results]\n",
            "acc, overfit, scores = zip(*scatter_data)\n",
            "scatter = axes[1].scatter(overfit, acc, c=scores, s=50, cmap='viridis', alpha=0.6, edgecolor='black')\n",
            "axes[1].set_xlabel('Overfit Gap (train-val)')\n",
            "axes[1].set_ylabel('Validation Accuracy')\n",
            "axes[1].set_title('Accuracy vs Generalization Gap')\n",
            "plt.colorbar(scatter, ax=axes[1], label='Score')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig(PHASE2_STAGE2_PLOT, dpi=150, bbox_inches='tight')\n",
            "plt.show()\n",
            "\n",
            "print(f'Saved: {PHASE2_STAGE2_PLOT}')\n"
        ]
    },
    {
        "cell_type": "markdown",
        "source": [
            "## Stage 3: Ensemble Methods\n",
            "\n",
            "Train multiple models with best hyperparams and different seeds for ensemble prediction.\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "print('\\n=== STAGE 3: Ensemble Training ===')\n",
            "\n",
            "# Note: Full ensemble training would be here\n",
            "# For now, we show the structure\n",
            "\n",
            "from feature_selection import train_one_pass, _train_sparse_gate\n",
            "\n",
            "n_ensemble = 5\n",
            "ensemble_seeds = [42, 43, 44, 45, 46]\n",
            "\n",
            "print(f'Training {n_ensemble} ensemble members with best config...')\n",
            "print(f'Best config: {stage2_best}')\n",
            "\n",
            "# Extract best config\n",
            "best_n_select = stage2_best['n_select']\n",
            "best_hidden_dims = stage2_best['hidden_dims']\n",
            "best_dropout = stage2_best['dropout']\n",
            "best_dist_lambda = stage2_best.get('dist_lambda', 0.1)\n",
            "best_model_type = stage2_best.get('model_type', 'focused')\n",
            "best_optimizer = stage2_best.get('optimizer_type', 'adam')\n",
            "best_lr = stage2_best.get('lr', 1e-3)\n",
            "best_label_smoothing = stage2_best.get('label_smoothing', 0.0)\n",
            "\n",
            "ensemble_models = []\n",
            "ensemble_val_accs = []\n",
            "\n",
            "# For each ensemble member, train on full data with different seed\n",
            "for seed_idx, seed in enumerate(ensemble_seeds):\n",
            "    print(f'\\nEnsemble member {seed_idx + 1}/{n_ensemble} (seed={seed})...')\n",
            "    \n",
            "    # Phase 1: select features on full data\n",
            "    model_p1, top_idx, _, _, _ = train_one_pass(\n",
            "        X, y, sample_weights_v2,\n",
            "        hidden_dims=best_selector_config['hidden_dims'],\n",
            "        l1_lambda=best_selector_config['l1_lambda'],\n",
            "        dropout=best_selector_config.get('dropout', 0.3),\n",
            "        n_select=best_n_select,\n",
            "        n_epochs=500,\n",
            "        device=str(device),\n",
            "        seed=seed,\n",
            "    )\n",
            "    \n",
            "    X_sel = X[:, top_idx].astype(np.float32)\n",
            "    \n",
            "    # Phase 2: train focused model\n",
            "    model_p2, _, _ = train_focused(\n",
            "        X_sel, y, sample_weights_v2,\n",
            "        hidden_dims=best_hidden_dims,\n",
            "        dropout=best_dropout,\n",
            "        n_epochs=600,\n",
            "        batch_size=64,\n",
            "        seed=seed,\n",
            "        device=str(device),\n",
            "        dist_lambda=best_dist_lambda,\n",
            "        model_type=best_model_type,\n",
            "        optimizer_type=best_optimizer,\n",
            "        lr=best_lr,\n",
            "        label_smoothing=best_label_smoothing,\n",
            "    )\n",
            "    \n",
            "    # Get terminal accuracy on full data\n",
            "    X_sel_t = torch.FloatTensor(X_sel)\n",
            "    y_t = torch.FloatTensor(y)\n",
            "    \n",
            "    metrics = eval_prediction_metrics(model_p2, X_sel_t, y_t, terminal_mask, device)\n",
            "    term_acc = metrics['argmax_accuracy']\n",
            "    \n",
            "    print(f'  Terminal accuracy: {term_acc:.4f}')\n",
            "    ensemble_models.append(model_p2)\n",
            "    ensemble_val_accs.append(term_acc)\n",
            "\n",
            "ensemble_mean_acc = np.mean(ensemble_val_accs)\n",
            "ensemble_std_acc = np.std(ensemble_val_accs)\n",
            "\n",
            "print(f'\\n=== Ensemble Summary ===')\n",
            "print(f'Mean terminal accuracy: {ensemble_mean_acc:.4f} ± {ensemble_std_acc:.4f}')\n",
            "print(f'Improvement from baseline (0.7574): +{(ensemble_mean_acc - 0.7574)*100:.2f}%')\n",
            "print(f'Target reached: {ensemble_mean_acc >= 0.80}')\n"
        ]
    },
    {
        "cell_type": "markdown",
        "source": [
            "## Stage 4: Ablation Studies\n",
            "\n",
            "Validate that improvements come from the right sources.\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "print('\\n=== STAGE 4: Ablation Studies ===')\n",
            "\n",
            "# Test Effect 1: dist_lambda removal\n",
            "print('\\nAblation 1: Effect of distance correlation loss (dist_lambda)...')\n",
            "\n",
            "ablation_grids = [\n",
            "    {\n",
            "        'name': 'No dist_lambda',\n",
            "        'grid': {\n",
            "            'n_select': [best_n_select],\n",
            "            'hidden_dims': [best_hidden_dims],\n",
            "            'dropout': [best_dropout],\n",
            "            'dist_lambda': [0.0],\n",
            "            'model_type': [best_model_type],\n",
            "            'optimizer_type': [best_optimizer],\n",
            "            'lr': [best_lr],\n",
            "            'label_smoothing': [best_label_smoothing],\n",
            "        }\n",
            "    },\n",
            "    {\n",
            "        'name': 'Current (with dist_lambda)',\n",
            "        'grid': stage2_best.copy(),\n",
            "    }\n",
            "]\n",
            "\n",
            "ablation_results_dist = []\n",
            "for ablation in [ablation_grids[0]]:\n",
            "    print(f\"  Testing: {ablation['name']}\")\n",
            "    res, _ = cross_validate_focused_improved(\n",
            "        X, y, sample_weights_v2, terminal_mask,\n",
            "        selector_config=best_selector_config,\n",
            "        param_grid=ablation['grid'],\n",
            "        n_splits=5,\n",
            "        selector_epochs=250,\n",
            "        focused_epochs=400,\n",
            "        seed=42,\n",
            "        device=str(device),\n",
            "    )\n",
            "    ablation_results_dist.append({\n",
            "        'condition': ablation['name'],\n",
            "        'mean_val_acc': res[0]['summary']['mean_val_acc'],\n",
            "        'overfit_gap': res[0]['summary']['mean_overfit_gap'],\n",
            "    })\n",
            "\n",
            "ablation_df = pd.DataFrame(ablation_results_dist)\n",
            "print('\\nAblation Results:')\n",
            "print(ablation_df.to_string(index=False))\n"
        ]
    },
    {
        "cell_type": "markdown",
        "source": [
            "## Final Summary\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "print('\\n' + '='*60)\n",
            "print('PHASE 2 HYPERPARAMETER OPTIMIZATION - FINAL SUMMARY')\n",
            "print('='*60)\n",
            "\n",
            "print(f'\\nBaseline (from protein_feature_select.ipynb):')\n",
            "print(f'  Hard-label validation accuracy: 0.7574')\n",
            "print(f'  Soft target probability: 0.5743')\n",
            "print(f'  Overfit gap: 0.1521')\n",
            "\n",
            "print(f'\\nStage 1 Results (Architecture Comparison):')\n",
            "print(f'  Best model: {stage1_results[0][\"config\"][\"model_type\"]}')\n",
            "print(f'  Validation accuracy: {stage1_results[0][\"summary\"][\"mean_val_acc\"]:.4f}')\n",
            "\n",
            "print(f'\\nStage 2 Results (Expanded Grid Search):')\n",
            "print(f'  Validation accuracy: {best_stage2_acc:.4f}')\n",
            "print(f'  Overfitting gap: {stage2_results[0][\"summary\"][\"mean_overfit_gap\"]:.4f}')\n",
            "print(f'  Soft target probability: {stage2_results[0][\"summary\"][\"mean_expected_target_probability\"]:.4f}')\n",
            "\n",
            "print(f'\\nStage 3 Results (Ensemble):')\n",
            "print(f'  Ensemble mean accuracy: {ensemble_mean_acc:.4f} ± {ensemble_std_acc:.4f}')\n",
            "\n",
            "print(f'\\n=== FINAL PERFORMANCE ===')\n",
            "total_improvement = ensemble_mean_acc - 0.7574\n",
            "improvement_pct = (total_improvement / 0.7574) * 100\n",
            "print(f'  Improvement: +{total_improvement*100:.2f}% ({improvement_pct:.1f}% relative)')\n",
            "print(f'  Target 80% achieved: {ensemble_mean_acc >= 0.80}')\n",
            "\n",
            "print(f'\\nBest Configuration:')\n",
            "for k, v in stage2_best.items():\n",
            "    print(f'  {k}: {v}')\n"
        ]
    },
    {
        "cell_type": "code",
        "source": [
            "# Save results to CSV for analysis\n",
            "results_summary = {\n",
            "    'stage': ['Baseline', 'Stage 1', 'Stage 2', 'Ensemble'],\n",
            "    'val_acc': [0.7574, stage1_results[0]['summary']['mean_val_acc'],\n",
            "                best_stage2_acc, ensemble_mean_acc],\n",
            "    'overfit_gap': [0.1521, stage1_results[0]['summary']['mean_overfit_gap'],\n",
            "                    stage2_results[0]['summary']['mean_overfit_gap'],\n",
            "                    np.nan],\n",
            "    'soft_target_prob': [0.5743, stage1_results[0]['summary']['mean_expected_target_probability'],\n",
            "                         stage2_results[0]['summary']['mean_expected_target_probability'],\n",
            "                         np.nan],\n",
            "}\n",
            "\n",
            "summary_df = pd.DataFrame(results_summary)\n",
            "summary_df.to_csv(PHASE2_OPTIMIZATION_SUMMARY_CSV, index=False)\n",
            "\n",
            "print(f'Saved summary to: {PHASE2_OPTIMIZATION_SUMMARY_CSV}')\n"
        ]
    }
]

# Write notebook\nif __name__ == '__main__':\n    # Note: This is template content\n    # The actual notebook will be created by the assistant\n    print('Notebook structure defined')\n